### ISSUE TITLE
Store playlists in database

### ISSUE THREAD

**Issue by morecchia** [morecchia/tonefolder-audio#19]
currently, a single playlist is stored in localStorage. 
Start storing playlists in database, allowing multiple playlists per user

**Comment by ritikBhandari** [comment]
Hi,
Can I take up this issue?

**Comment by morecchia** [comment]
Hi, this is basically a personal project, so your changes won't get merged.  However, you are free to fork this and develop on your own. As you can probably see ,there is no backend in this repo, so I'd be interested in seeing your implementation.  Thanks for the interest.
